# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: DockerCompose@1
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure subscription 1(2)(73d53848-bb3c-4d47-a43d-8ed52ad3956d)'
    azureContainerRegistry: '{"loginServer":"tanukismiteleague.azurecr.io", "id" : "/subscriptions/73d53848-bb3c-4d47-a43d-8ed52ad3956d/resourceGroups/Django/providers/Microsoft.ContainerRegistry/registries/TanukiSmiteLeague"}'
    dockerComposeFile: '**/docker/docker-compose.yml'
    projectName: 'tsl'
    action: 'Run a Docker Compose command'