version: '3.8'

services:

  terra:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: terra
    entrypoint: /data/terra/startTerra.sh
    image: terra:1.0
    ports:
      - "8000:8000"

  mercury:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: mercury
    entrypoint: /data/mercury/startMercury.sh
    image: mercury:1.0
    ports:
      - "8000:8000"

  janus:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: janus
    image: janus:1.0
