version: '3.8'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  terra:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: terra
    entrypoint: /data/terra/startTerra.sh
    environment:
      - BUILD_TYPE=dev
    image: terra:1.0
    ports:
      - "8000:8000"
    volumes:
      - ../athena/mount:/data/terra/mount

  thoth:
    build:
      context: ../
      dockerfile: docker/thoth/Dockerfile
      target: thoth
    entrypoint: uvicorn thoth.main:app --host 0.0.0.0 --port 8002
    environment:
      - BUILD_TYPE=dev
    image: thoth:1.0
    ports:
      - "8002:8002"
    volumes:
      - ../athena/mount/thoth:/mount

  mercury:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: mercury
    entrypoint: /data/mercury/startMercury.sh
    environment:
      - BUILD_TYPE=dev
    image: mercury:1.0
    ports:
      - "80:80"      
    volumes:
      - ../athena/mount:/data/mercury/mount
      

  janus:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: janus
    environment:
      - BUILD_TYPE=dev
    image: janus:1.0
    volumes:
      - ../athena/mount:/data/janus/mount
      - ../athena/logs:/data/janus/logs

volumes:
  mercury-athena:
    external: true
