# Generated by Django 5.1 on 2024-08-08 21:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('captain_id', models.AutoField(primary_key=True, serialize=False)),
                ('smite_name', models.CharField(max_length=32)),
                ('team_name', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=256)),
                ('captain_budget', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2001, 11, 5, 0, 0))),
                ('title', models.CharField(default='Glaeria Smite League', max_length=64)),
                ('description', models.CharField(default='None', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('discord_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('smite_name', models.CharField(max_length=32)),
                ('role_1', models.CharField(default='Fill', max_length=16)),
                ('role_2', models.CharField(default='Fill', max_length=16)),
                ('smite_guru', models.CharField(max_length=128)),
                ('estimated_value', models.IntegerField(default=0)),
                ('captain_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talaria.captain')),
                ('tournament_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talaria.tournament')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaria.user')),
            ],
        ),
        migrations.AddField(
            model_name='captain',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaria.tournament'),
        ),
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('suggested_value', models.IntegerField(default=0)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaria.player')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaria.user')),
            ],
        ),
        migrations.AddField(
            model_name='captain',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaria.user'),
        ),
    ]
